import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/redux/store";
import AppProvider from "@/redux/AppProvider";
import { Home, MonitorSmartphone, UserRound } from "lucide-react";
import { FloatingNav } from "@/components/ui/aceternity/FloatingNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navRoutes = [
  {
    name: "Home",
    link: "/",
    icon: <Home className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "About",
    link: "/about",
    icon: <UserRound className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Contact",
    link: "/contact",
    icon: <MonitorSmartphone className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <AppProvider>
        <body className={`${inter.className}`}>
          <FloatingNav navItems={navRoutes} />
          {children}
        </body>
      </AppProvider>
    </html>
  );
}
